### ISSUE TITLE
Feature: User can create a new post 

### ISSUE THREAD

**Issue by jeesupark96** [jeesupark96/finalproject#2]
## ⚙️ Feature

User can create a new post about an experience 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The User can fill out a form and display the information through a post. They will be able to give a name, rating, description and geo pin the location of the event as well. 

## 🖼️ Wireframes

<img width="139" alt="image" src="https://user-images.githubusercontent.com/90468158/154345734-6fe7717d-dd7c-4d33-9961-979a7fc02b39.png">

<img width="500" alt="image" src="https://user-images.githubusercontent.com/90468158/154346345-4883236f-94d5-41b5-9504-d68406527e1e.png">

## ✅ Task List

- [ ] Create a component to fill out a form 
- [ ] Update component to input Title, Rating, GeoPin, description and upload photos 
- [ ] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [ ]  Make all inputs of the entry form required.
- [ ]  Listen for 'input' events on the photoUrl input to update the src attribute of the photo preview when the input value changes.
- [ ] Ensure that each form entry has a spotId for the geotag

### 🧑‍⚕️ Clean Up

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
