### ISSUE TITLE
Feature: User can edit an entry

### ISSUE THREAD

**Issue by jeesupark96** [jeesupark96/finalproject#3]
## ⚙️ Feature

User can edit an entry that they previously made. 

## 📐 Functionality

A user can update and edit a previously made entry and display the new info

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

- [ ]  Listen for clicks on the parent element of all rendered entries.
- [ ] Show the entry form if an edit icon was clicked.
- [ ] Find the matching entry object in the data model and assign it to the data model's editing property if an edit icon was clicked.
- [ ] Pre-populate the entry form with the clicked entry's values from the object found in the data model.
- [ ]  Update the entry form's submit handler function to conditionally add a new entry object or update the existing one.
- [ ] Update the entry form's submit handler function to conditionally add a new entry DOM tree or replace the existing one.

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
